### PR TITLE
[FIX] use git to update MACS

### LINKED ISSUE #1225: [BUG] macstoolbox during stats step in parfor not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux Ubuntu 22.04 "jammy jellyfish"

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2018a

### bidspm version

v3.1.0

### bidspm branch / commit number

branch =

    'main'

commit =

    '94a83c9e'

### Expected Behavior

_No response_

### BIDS stats model

_No response_

### Current Behavior & Error message

```matlab
% copy the error you got below
% before the three backticks (```)


cp: cannot create regular file '/home/marcobarilari/data/tools/spm12/toolbox/MACS/batch_MA_LFE_group_auto.m': File exists



```

### Anything else?

the erros message is repeated for all the jobs

### PR DESCRIPTION
**Pull request by Remi-Gau**
- closes #1225

### CODE REVIEW

File: src/infra/checkToolbox.m [hunk 1]
```diff
@@ -65,7 +65,7 @@
 
       if ~status && install
 
-        installMacstoolbox(opt);
+        updateMacstoolbox(opt);
```
Comment (Remi-Gau) [inline src/infra/checkToolbox.m:68]:
```suggestion
        updateMacstoolbox();
```
